services:
  app:
    build: .
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/todoapp
      - JWT_SECRET=hello
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
